#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

. usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

for x in ehci-hcd ohci-hcd uhci-hcd usbhid xhci hid-apple \
hid-cherry hid-logitech hid-microsoft \
vfat; do
	manual_add_modules "${x}"
done

copy_modules_dir kernel/drivers/usb/storage

copy_exec /usr/bin/vim.basic /bin/rvim
copy_exec /bin/nano /bin/rnano

cp -p usr/share/initramfs-tools/bin/runeditor ${DESTDIR}/bin

# copy terminfo
mkdir -p ${DESTDIR}/lib/terminfo/l
cp -p /lib/terminfo/l/linux ${DESTDIR}/lib/terminfo/l

mkdir ${DESTDIR}/text

